// keep codes in ONE place
export const PERMS = {
  RBAC_MANAGE: 'RBAC_MANAGE',
  DEALERS_READ: 'DEALERS_READ',
  DEALERS_WRITE: 'DEALERS_WRITE',
  DEALERS_REVIEW: 'DEALERS_REVIEW',
  FIN_READ: 'FIN_READ',
  FIN_WRITE: 'FIN_WRITE',
  FIN_REVIEW: 'FIN_REVIEW',
  FIELDS_MANAGE: 'FIELDS_MANAGE',
  LAND_READ: 'LAND_READ',
  LAND_WRITE: 'LAND_WRITE',
  LAND_REVIEW: 'LAND_REVIEW',
  CUSTOMERS_READ: 'CUSTOMERS_READ',
  CUSTOMERS_WRITE: 'CUSTOMERS_WRITE',
  DOCS_READ: 'DOCS_READ',
  DOCS_WRITE: 'DOCS_WRITE',
};
